### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [dart-lang/convert#13]
When running tests in dart 2 mode, see the following

type 'List<dynamic>' is not a subtype of type 'List<int>' of 'chunk' where...
type 'List<dynamic>' is not a subtype of type 'List<int>' of 'chunk' where
  List is from dart:core
  List is from dart:core
  int is from dart:core
package:convert/src/byte_accumulator_sink.dart                                          ByteAccumulatorSink.addSlice
../../tdart/convert/test/byte_accumulator_sink_test.dart 43:10  main.<fn>

**Comment by natebosch** [comment]
Closing since this package has tests running in Dart 2.
