### ISSUE TITLE
json.decode can't parse integers over 64 bit

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/convert#19]
I'm trying to do the following

```
const payload = '{"connectionID":15852666135343119227}';
print(json.decode(payload));
```

prints
```
{connectionID: 15852666135343118000.0}
```

A json number [is not limited](https://stackoverflow.com/questions/13502398/json-integers-limit-on-size) to only 64 bits.

Is there currently a workaround for that?

**Comment by lumi-sch** [comment]
JSON is based on the JS spec. The JS spec explicitly limits the accuracy guarantee for integers to a maximum of 9007199254740991. This is most definitely not a bug.

**Comment by modulovalue** [comment]
My problem is that I'm using a third-party API [systemStatus at Kraken WebSocket API](https://www.kraken.com/features/websocket-api#message-systemStatus) over which I have no control.

Furthermore, I'm using over a dozen of cryptocurrency-related APIs and that example shows me that they may expect their integers to go beyond 64 bits as many of them use pure numbers instead of strings for values that can quite possibly go beyond 64 bits.

[RFC7159](https://www.rfc-editor.org/rfc/rfc7159.txt)
> This specification allows implementations to set limits on the range
   and precision of numbers accepted.

[StackOverflow: JSON integers: limit on size](https://stackoverflow.com/questions/13502398/json-integers-limit-on-size)
> Since JSON is an abstract format that is not exclusively targeted at JavaScript, the actual target environment determines the boundaries of what can be interpreted.

Does it mean that I'll have to find an alternative JSON parser for APIs over which I have no control and which do not adhere to the JavaScript/Dart JSON number interpretation?

I'd like to suggest a solution if there's no workaround for this problem.
Dart has a [BigInt](https://api.dartlang.org/stable/2.2.0/dart-core/BigInt-class.html) class. [Dart also used to support integers of arbitrary precision](https://www.dartlang.org/articles/server/numeric-computation). Wouldn't it make sense to at least have an alternative JsonDecoder/Encoder for JSON interpretations that expect numbers to be of arbitrary precision?

**Comment by iampawan** [comment]
Facing the same issue. I have to send encoded json to the API which has BigInt type data
