### ISSUE TITLE
Problem with percent.encode()

### ISSUE THREAD

**Issue by amebrahimi** [dart-lang/convert#23]
Hello, I have a problem with percent.encode().
I have an API that is used by the Arabs and can contain Arabic characters. One of the Arabic characters is "خ" and if I want to convert it with this method `percent.encode('خ'.codeUnits)`. The code unit number is 1582 which represents 0x62e in hexadecimal. In this case, I will get an exception because it's out of range of the bytes that this library can convert. and I have this exception `Unhandled Exception: FormatException: Invalid byte 0x62`. Can you please help me with my problem? are there any alternatives I can use?

**Comment by amebrahimi** [comment]
I have found a solution, I've used Uri.encodeQueryComponent(data). It did the trick

**Comment by natebosch** [comment]
`String.codeUnits` does not give a list of bytes. `Uri.encodeQueryComponent` is a fine solution. Another option would be `percent.encode(utf8.encode('خ'))`. where `utf8` is from `dart:convert`.

**Comment by amebrahimi** [comment]
@natebosch `String.codUnits` gives a list of ints, My bad. thank you for your response. And thank you for the other option you gave me worked. Can you please explain what is the difference between Uri.encodeQueryComponent and percent.encode.

**Comment by natebosch** [comment]
`Uri.encodeQueryComponent` will encode a space to `+` instead of `%20` like `percent.encode(utf8.encode(string))` will. I'm not aware of any other differences, but I could be overlooking something.
