### ISSUE TITLE
Unable to encode Arabic text using hexEncoder or Base64Encoder

### ISSUE THREAD

**Issue by charbelmkh** [dart-lang/convert#24]
Hello, 
I'm and android developer and I have recently decided to move to dart/flutter,

I'm currently facing a problem where i cannot encode (Hex or base64) Arabic text
below is my sample code 

-------------dart hexEncoder---------------------
 HexEncoder hexEncoder = hex.encoder;
 String utf8Data = 'شربل';
String hexData = hexEncoder.convert(utf8Data.codeUnits);
-------------dart hexEncoder---------------------

-------------dart runtime error---------------------
Testing started at 1:56 PM ...

package:convert/src/hex/encoder.dart 78:5   _convert
package:convert/src/hex/encoder.dart 22:38  HexEncoder.convert
test/security_encryption_test.dart 19:33    main.<fn>

FormatException: Invalid byte 0x634. (at offset 0)

[flutter_doctor.log](https://github.com/dart-lang/convert/files/4563764/flutter_doctor.log)

**Comment by natebosch** [comment]
Dart Strings are UTF-16, not UTF-8. See the doc comment for `String.codeUnits` which mentions it uses UTF-16: https://api.dart.dev/stable/2.8.3/dart-core/String/codeUnits.html

To get a list of bytes from a String, encode with utf8.

```dart
var string = 'شربل';
var bytes = utf8.encode(string);
var hexData = hex.encode(bytes);
```
