### ISSUE TITLE
Traversing with level of traversed objects, without accumulation

### ISSUE THREAD

**Issue by darkstarx** [dart-lang/convert#27]
What if I need traverse a json looking for specific objects based on <key, value, level of nesting>?
We have the reviver in JsonDecoder, but it does not provide the level of <key, value> and accumulate the resulting object (with useless memory consumption) that I won't need.

**Comment by lrhn** [comment]
Traversing a JSON source is a rather specialized job, not something that's necessarily a *converter*.

Try looking at [`package:jsontool`](https://pub.dev/packages/jsontool) which is built to traverse JSON source without necessarily parsing it.
