### ISSUE TITLE
Percent encode unexpectedly encodes numbers

### ISSUE THREAD

**Issue by DanTup** [dart-lang/convert#3]
I'm integrating with the twitter API which describes that data should be "percent encoded". In C# I found that the method that matched Twitters docs was `Uri.EscapeDataString`. I'm trying to do the same thing in Dart and discovered that none of them methods on the `Uri` class behaved correctly, but someone pointed me at this package.

This seems to work great for all the characters I've tried, except numbers:

```dart
// Dart:
print(percent.encode("1".codeUnits)); // outputs %31
```

```csharp
// C#:
Console.WriteLine(Uri.EscapeDataString("1")); // outputs 1
```

The C# version seems to match twitter definition of "percent encoding" but I'm struggling to find detailed docs on whether this is a standard and if so, which is correct. I'm raising it here in the hope that either a) it's a bug and can be fixed or b) there's another method I want that behaves as C# does/twitter expects.

**Comment by DanTup** [comment]
On Google+ someone pointed out that the Dart docs say this is compatible with [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt), which contains:

> **2.3.  Unreserved Characters**
> 
> Characters that are allowed in a URI but do not have a reserved purpose are called unreserved.  These include uppercase and lowercase letters, decimal digits, hyphen, period, underscore, and tilde.
>
>      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
>
> [...]
>
> For consistency, percent-encoded octets in the ranges of ALPHA (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E), underscore (%5F), or tilde (%7E) should not be created by URI producers

This leads us to believe this is a bug in the implementation and they should *not* be encoded.

**Comment by lrhn** [comment]
Definitely a bug. The encoder contains the following code to detect characters that should not be encoded:
```
if ((letter >= $a && letter <= $z) ||
        byte == $dash ||
        byte == $dot ||
        byte == $underscore ||
        byte == $tilde) {
```
It clearly fails to catch digits. Bad testing! Shame!

**Comment by DanTup** [comment]
@lrhn I've sent #4 to extend tests and fix this but not sure if I need to get it reviewed on the Chromium code review site?
