### ISSUE TITLE
hex can't decode odd length strings

### ISSUE THREAD

**Issue by peekpt** [dart-lang/convert#56]
hex.decode("1")-> fail
hex.decode("01")-> ok

since toRadixString(16) converts 1 into "1" it makes a problem converting again to List<int> with hex.decode

Solution:
-Count the String.length, if it's odd, do padLeft(srtLength+1,'0')

If this is implemented by default it will prevent bug from happening.

Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (12 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by lrhn** [comment]
Not planning to change this.

The way to invert `var string = number.toRadixString(16);` is `var number = int.parse(string, radix: 16)`.

The hex encoding is a *byte* encoding, not a general integer encoding. It uses two hex digits per byte.
