### ISSUE TITLE
jsonarray decode gets error: flutter: FormatException

### ISSUE THREAD

**Issue by heliping** [dart-lang/convert#58]
the json string like this :
`[
  {
    "A": "bbbb",
    "B": "11817"
  },
  {
    "A": "bbbb",
    "B": "11817"
  }
]`

when decode by convert,
` else if (json.startsWith("[")) {
      //is jsonArray
      
      List decode = const JsonCodec().decode(json);
..............`
the error found:

flutter: FormatException: Unexpected character (at character 3)
[{A: bbbb, B: 11817}, {A: bbbb, B: 11817}]
  ^
json: [{A: bbbb, B: 11817}, {A: bbbb, B: 11817}]`

**Comment by natebosch** [comment]
> Unexpected character (at character 3)

I think the String you are passing to `decode` is not exactly the content you think it is. Likely its `[{A` without the quotes as required for JSON

If I define a string like `final input = '[ { "A": "bbbb", "B": "11817" }, { "A": "bbbb", "B": "11817" } ]';` then it decodes correctly.
