### ISSUE TITLE
Uncaught Error: Converting object to an encodable object failed: Instance of 'MappedListIterable<int, String>'

### ISSUE THREAD

**Issue by nank1ro** [dart-lang/convert#61]
Hi,

I have an issue with mapped iterables, the conversion fails with the error:
> Uncaught Error: Converting object to an encodable object failed: Instance of 'MappedListIterable<int, String>'

Here it is a sample code to reproduce the issue:
```dart
import 'dart:convert';

void main() {
  final Iterable<int> items = [1,2];
  final items2 = items.map((i) => i.toString()); 
  print(jsonEncode(items2));
}
```

for now to make it working I simply have to add a `.toList()` after the mapping.

**Comment by natebosch** [comment]
This is working as intended. I don't think we want to support `.toJson` on general Iterables, since they could be unbounded. A `List` can be converted to json (if the elements can be converted) and you'll get a List back when you deserialize - there is no way to deserialize to an Iterable.
