### ISSUE TITLE
jsonEncode error when convert with Int64 instance.

### ISSUE THREAD

**Issue by SittiphanSittisak** [dart-lang/convert#78]
The data from MongoDB this data contains a value Int64 type.
This data can't convert to json via `jsonEncode` function.
The error message is:
```
Converting object to an encodable object failed: Instance of 'Int64'
```
Is it a bug or not support?

**Comment by SittiphanSittisak** [comment]
I am using it:
```
import 'package:fixnum/fixnum.dart';

int? toInt(dynamic value) {
    try {
      if (value == null) return null;
      if (value is int) return value;
      if (value is Int32) return value.toInt();
      if (value is Int64) return value.toInt();
      if (value is num) return value.toInt();
      return int.tryParse(value.toString());
    } catch (_) {
      return null;
    }
  }
```

**Comment by rakudrama** [comment]
You should almost never use `Int64.toInt()`.

On the **web platform**, this line truncates the value, leading to data corruption:

    if (value is Int64) return value.toInt();

The returned value will be a JavaScript Number, which is an IEEE 754 double, which has an effective safe-integer range of 52 bits. 

Test with `Int64.parseHex('7FFF000022221111')`. The truncated `int` value will be nearer `0x7FFF0000022221000`.

For more information, see https://dart.dev/guides/language/numbers
