### ISSUE TITLE
Get this error

### ISSUE THREAD

**Issue by tejainece** [dart-lang/convert#8]
```
'package:convert/src/percent/encoder.dart': malformed type: line 23 pos 13: cannot resolve class 'ChunkedConverter' from 'PercentEncoder'
    extends ChunkedConverter<List<int>, String, List<int>, String> {
```

**Comment by khalios082** [comment]
I have the same problem like you but seems there is no answer but i may be interested to know if you found a solution are u using something like that 
![captura](https://user-images.githubusercontent.com/35984302/36002685-04da433e-0cf9-11e8-9241-d43b996846a3.PNG)
?

**Comment by khalios082** [comment]
even if i update the sqljocky to current version i get the same problem

**Comment by deepakshrma** [comment]
i added  convert: ^2.0.0 in pubspec.yaml it resolve the issue.
